### ISSUE TITLE
extension for length of video

### ISSUE THREAD

**Issue by liveaspankaj** [liveaspankaj/xapi-video-cop#1]
@jhaag75, as discussed in today's meeting we need to add an additional extension for length of the video. 

should we use "length" or do you have a better alternative. 
you had once suggested "video-length" but it might not be good for audios, so if we can have a neutral name, it would be best.

**Comment by jhaag75** [comment]
duration or video-duration?

**Comment by liveaspankaj** [comment]
duration is good. but we have "duration" for the amount of time user spent watching the video. Its not a separate extension but result.duration but still, two durations can be confusing.

**Comment by jmkevan** [comment]
I would say length is common US vernacular.

- J

Jonathan Kevan
R&D Coordinator, Distance Course Design & Consulting (DCDC)
College of Education, University of Hawai‘i at Manoa
1776 University Avenue, Wist 245, Honolulu, Hawai‘i 96822
Web: dcdc.coe.hawaii.edu


------ Original Message ------

**Comment by jhaag75** [comment]
ok you convinced me.... video-length or length sounds good

**Comment by liveaspankaj** [comment]
we have a decision to use "length" extension.
