### ISSUE TITLE
Is the Wiki Welcome correct? mentions Web conference 1st Tuesday of every month at 2:30am-3:30am US Eastern Time 

### ISSUE THREAD

**Issue by seakintruth** [liveaspankaj/xapi-video-cop#2]
https://github.com/liveaspankaj/xapi-video-cop/wiki

Is there actually a Web conference 1st Tuesday of every month at 2:30am-3:30am US Eastern Time?

everywhere else mentions Date: 1st Monday, Every Month and Time: 3:00 PM - 4:00 PM, US Eastern Time

**Comment by liveaspankaj** [comment]
Hi @seakintruth 

It is 1st Monday, Every Month and Time: 3:00 PM - 4:00 PM, US Eastern Time

Pankaj

**Comment by seakintruth** [comment]
I've updated the [wiki](https://github.com/liveaspankaj/xapi-video-cop/wiki) page to reflect that, additionally Tuesday is still listed on the sites:
https://groups.google.com/forum/#!forum/xapi-video-cop
and 
http://www.adlnet.gov/videos-cop

**Comment by liveaspankaj** [comment]
Thanks @seakintruth 

@jhaag75 are you able to update the information on  http://www.adlnet.gov/videos-cop
meeting day and meeting link is old there.

**Comment by jhaag75** [comment]
Yes, let me know what I should add/ update

**Comment by liveaspankaj** [comment]
@jhaag75  here are the changes: 

1.  
Tuesdays
to
Mondays

2. Meeting link change to: 
https://www.nextsoftwaresolutions.com/VideoCoPMeeting/

3. View CoP Videos website link change to: 
https://liveaspankaj.gitbooks.io/xapi-video-profile/content/

Thanks
